### ISSUE TITLE
default header-navigation template produces invalid markup

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#156]
The default `header-navigation.phtml`

https://github.com/FACT-Finder-Web-Components/magento2-module/blob/13d96c851d8e3dcef860f8b768797a053ffb92be/src/view/frontend/templates/ff/header-navigation.phtml#L1-L23

currently produces invalid markup, since it is nesting other HTML elements between `<ul>` and `<li>`. The only allowed parents for `<li>` are `<ol>` and `<ul>` and the only allowed children for `<ul>` are `<li>`.

https://www.w3.org/TR/2012/WD-html-markup-20121025/ul.html#ul-content-model

**Comment by fmarangi** [comment]
@fritzmg thanks for your report. It is actually a known issue, the `ff-navigation` was implemented quickly in response to a customer request, and it was written like this to take advantage of Luma CSS and Magento JS components without huge effort.

Mostly this template would be rewritten in a custom theme implementation, and the default menu JS/CSS replaced with something more modern and flexible (Luma is just bad here). I can see 2 options for this issue:
* we write correct markup, together with custom JS for the behaviour and some CSS, which would be good for Luma but has to be overridden in a custom theme
* add comments regarding the markup in the template, so that our intention there is clear

**Comment by fritzmg** [comment]
Hm.. does it _need_ to be compatible with the Luma theme by default? Are other FACT-Finder components compatible as well? Imho the FACT-Finder Magento 2 module should use as little CSS and JavaScript as possible.

Though the FACT-Finder Web Components are to blame here as well. They include a lot of inline CSS and JavaScript functionality, making customizations more difficult.

Also I just noticed that something like this is hardcoded into the Magento 2 module as well:

https://github.com/FACT-Finder-Web-Components/magento2-module/blob/13d96c851d8e3dcef860f8b768797a053ffb92be/src/view/frontend/web/js/search-navigation.js#L27-L40

**Comment by fmarangi** [comment]
@fritzmg we tried to get rid of header navigation, and tried to reimplement that with #161. LIke this we leave navigation and routing to Magento for better SEO, and render categories with FF. What do you think about it?

**Comment by a-laurowski** [comment]
I'm closing this ticket as template and js mentioned before has been removed in new version of module.
https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v1.3.0
Feel free to reopen if there's still  issues with markup validation

**Comment by fritzmg** [comment]
Sorry, I did not have time to review the changes, but it sounds good :)
