### ISSUE TITLE
Use of self and private

### ISSUE THREAD

**Issue by GuillaumeBrook** [FACT-Finder-Web-Components/magento2-module#239]
Hello,

You are respecting the majority of Magento 2 best practices and the code is clean.
However, the use of private is not deprecated but usually borring for developpers.

While overriding Omikron\Factfinder\Controller\Router, I wanted to change
`public const  FRONT_NAME         = 'FACT-Finder';`
The associated function does :
`private function isValidRequest(RequestInterface $request): bool
    {
        return !$request->getControllerName() && preg_match('#^(/' . self::FRONT_NAME . '/)#', $request->getPathInfo());
    }`

In my own class inheriting from yours I can't override the constant because it's use `self` and not `$this`.
Second problem I have to write completely `isValidRequest` but since it's private I have also to write completely the function `match` and since it used another private variable `$actionFactory` ... Well I rewrited the entire class just because `self` isn't `$this` and others private.

I have no other example right now since I'm beginning the modification of the module, but the use of "private" is **really** borring most of the time, `protected` is preferred.

Could you in a future update modify this class at least ?
Thank you

**Comment by fmarangi** [comment]
You shouldn't refer to constants with `$this` anyway, since it's public you can easily access it with `\Omikron\Factfinder\Controller\Router::FRONT_NAME`. Since it's a constant and it's public it shouldn't change in the future, so it's api-like.

The problem is, when we define something with `protected` we open up things for extension, and once we do that we have to keep it into account when we refactor something, i.e. if we change the implementation, your extension might fail. Therefore I'm very careful about such changes. You might try to create a PR and we can discuss your suggestions together. The class you mentioned is actually quite trivial, it's no big deal to extend it or swap it with your implementation via DI, just redefine this https://github.com/FACT-Finder-Web-Components/magento2-module/blob/master/src/etc/frontend/di.xml#L6

**Comment by fmarangi** [comment]
In case you need more help, just write me an email (see .mailmap) and i can provide you with some examples!

**Comment by GuillaumeBrook** [comment]
Yes I can access it directly like you said but I still have to rewrite the entire class because the function using the constant is private, and the other public method won't find my private, so I have to rewrite it too.
Still, yes it's trivial in this case, and it's only 50 lines of code, but it could be much more.

I get your point on maintainabilty, I'd rather have troubles when updating than rewriting entire classes for a little change. Depend of the point of view I guess!

It's noted for the PR and the email.

**Comment by fmarangi** [comment]
The implementation was changed considerably since this issue, closed because outdated.
