### ISSUE TITLE
checkout_submit_all_after observer only executed via API

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#248]
- FACT-Finder-Web-Components Magento2-Module version: **1.5.1** (also affects current version)
- Magento edition and version: **2.3.2 CE**
- PHP version: **7.1**
- Expected behavior: `Omikron\Factfinder\Observer\Tracking\Checkout` should be executed whenever `checkout_submit_all_after` is dispatched 
- Actual behavior: `Omikron\Factfinder\Observer\Tracking\Checkout` is only executed when `checkout_submit_all_after` is dispatched via REST API

Currently the `Omikron\Factfinder\Observer\Tracking\Checkout` is only registered via `etc/webapi_rest/events.xml`. This means checkout tracking is only done, when the order is placed via Magento's REST API, like it is done in the default implementation of Magento's One Page Checkout.

However, if you use a custom checkout method in the front end that does _not_ use the REST API to place the order, checkout tracking will never take place.

To solve this, may be simply register the observer also in `etc/frontend/events.xml`?

**Comment by a-laurowski** [comment]
Hi @fritzmg 
Thank you for your feedback.
Since the module codebase is intended to work with Magento2 default installation, we find no reason in adding such definitions other areas.

Although We understand this might bring troubles while using custom checkouts and that's why put proper information in module [README]( https://github.com/FACT-Finder-Web-Components/magento2-module/blob/master/README.md#tracking-event-listeners) about tracking listeners telling users how to adjust events definition in that case.

**Comment by fritzmg** [comment]
I don't get your position, to be honest. Your extension wants to track _any_ purchases, correct? So why not make sure, by default, that this is the case, no matter what?
