### ISSUE TITLE
Similar Products not shown

### ISSUE THREAD

**Issue by sja-dS** [FACT-Finder-Web-Components/magento2-module#316]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 
1.6.5.1 (1.1.3 NG)
- Magento edition and version: 
Commerce 2.4
- PHP version:
- 7.4
- Expected behavior: 
Displaying similar Products on PDP
- Actual behavior: 
No similar Products are shown, even with activated WebComponent
- Steps to reproduce:
Go to e.g. https://www.myagrar.de/agil-s.html
In the Network Inspector Tab you can see, that only the Recommandation Request is sent and nothing to request similar Products.

According to the [Documentation](https://web-components.fact-finder.de/api/4.x/ff-similar-products#tab=docs) Field Roles are also created and enabled for similar search.

**Comment by a-laurowski** [comment]
Hi @sja-dS 
Thanks for the reporting. The reason was the missing `idType` attribute of `ff-similar-products` element, which starting from Web Components [3.15.10](https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/3.15.10)
is mandatory when using NG. Please check the [change](https://github.com/FACT-Finder-Web-Components/magento2-module/pull/317/files#diff-cfb340b38a56bf6ac3f1cf4d45902100347a3f4b66b8d29b5cab8142d93c2a57L7).

If you not using our default template, just add this attribute to your custom one. Otherwise this fix will be released in new version on Friday.

**Comment by a-laurowski** [comment]
Released in major versions 
* [2.0.1]( https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v2.0.1)
* [1.6.7](https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v1.6.7)
