### ISSUE TITLE
Variant Products does not contain additioinal attributes in Feed

### ISSUE THREAD

**Issue by mbloss-dotsource** [FACT-Finder-Web-Components/magento2-module#321]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 
->omikron/magento2-factfinder
"version 1.6.5
-> omikron/magento2-factfinder-ng"
"version": "1.1.3

- Magento edition and version: 2.4.0 Commerce

- PHP version: 7.4

- Expected behavior: 
configurated additional attributes are available also on variant products of configurabe product in feed

- Actual behavior: 
additional attributes are only available on configurable master product in feed. Variant products only have attributes for variant configuration in feed column "Attributes"

- Steps to reproduce: 
1. create some configurable products
2. configure some additional attributes in "Stores -> Configuration -> Catalog -> Factfinder -> Export Settings ->Select Additional Attributes"
3. generate feed

**Comment by a-laurowski** [comment]
Hi @mbloss-dotsource  and thanks for reporting.
In fact this is a desired behavior. Master product (configurable) stores all attributes and the configurable options. Variants stores only these options they are configured with. In default setup this should works as expected because the master products are the only one rendered on the listing, and user can filter them by all of the configurable options.

 Can i ask you what is the reason you want to export the attributes from variant level?

**Comment by mbloss-dotsource** [comment]
Hi,

we need an special status attribute also on variant products, because we have some special price display logic for configurable products depending on variant values. So we want to display diffent text depending on the values that we get back in the variant array in search, but this is only availabe in search result if the attribute is send to fact finder via the feed.

**Comment by a-laurowski** [comment]
Hi @mbloss-dotsource 
thanks for clarification. We decided to add a mechanism which allows user to specify which fields should be exported on a variant level and which not.
I'll get back here once we finish with this

**Comment by a-laurowski** [comment]
hi @mbloss-dotsource 
Possibility to export attribute values stored in variants is now released in [v1.7.0](https://github.com/FACT-Finder-Web-Components/magento2-module/releases/tag/v1.7.0)
