### ISSUE TITLE
Filtering hides applicable Filters

### ISSUE THREAD

**Issue by sja-dS** [FACT-Finder-Web-Components/magento2-module#335]
- FACT-Finder-Web-Components Magento2-Module version (see composer.json): 1.6.8 with NG 1.1.3 and 2.1 (NG)
- Magento edition and version: Enterprise with B2B Extension
- PHP version: 7.4
- Expected behavior: After clicking a Filter on a PLP, all other applicable Filters are still shown
- Actual behavior: After clicking a Filter, only 1 Filter is shown
- Steps to reproduce: 
1. Open a PLP, e.g. https://www.myagrar.de/saatgut/ and you have a bunch of Filters
<img src="https://user-images.githubusercontent.com/84079139/129329814-bbeaa650-f2f4-4ce7-8cb2-20579190d02a.png" width="100" height="300">
2. Select a Filter, e.g. Greeningfähig = Yes and there is only 2 Filter left 
<img src="https://user-images.githubusercontent.com/84079139/129330363-b7c8f9ec-f645-45dc-92e2-195585eed39a.png" width="200" height="100">
3. When doing the same into the Demoshop, much more Filters are still shown
<img src="https://user-images.githubusercontent.com/84079139/129330780-74045e33-9dd5-43c4-b42b-cf79dfeb4a6f.png" width="100" height="300">

**Comment by a-laurowski** [comment]
Hi @sja-dS  
You have to contact a person from Project Development department dedicated to your project . Response from FACT-Finder is already returning two filters so there is not much we can actually do :/
![image](https://user-images.githubusercontent.com/4511883/130905040-f84e381e-7962-4303-b1c2-8624aa10619d.png)

**Comment by sja-dS** [comment]
Hey @a-laurowski 
Meanwhile we got some Feedback from our "Agent". Maybe this helps you, or you can give me a hint, how we can change this:
When you click a Filter a Search Request is sent. Something like this:
https://<FF-Server>/fact-finder/rest/v3/**_search_**/<Channel>?query=%2a&filter=CategoryPath%3ASaatgut%2FKulturen%2FBl%C3%BCh-+und+Wildackermischungen&sid=H71VKsqMQgHK51Bt4w45PGBAo9payL&format=json
With this, a Search Result is shown with much less Filters.
Is it possible to change this, that an navigation and not a search Request will be sent?
He thinks that's the main Reason for this Behaviour.

Thanks in advance.

**Comment by a-laurowski** [comment]
Hi @sja-dS 
This is ongoing topic in Web Components Development. In near future there will be provided solution which allows Web Components to "detect" when user is on category page and when on search result page. With that, any search-like requests will use navigation instead of search.

For the time being is this possible for you to enable this "navigation only" filters also for search? According to PD this configuration was not made by them and they cant tell if this is done for purpose or not.

**Comment by sja-dS** [comment]
Hey @a-laurowski 
Thanks for your Feedback. I send this to my Colleague und talk with them about the further steps.
Are there any plans when you're doing the Adjustment?

**Comment by a-laurowski** [comment]
Hi @sja-dS  
We are still discovering new cases within the "Navigation Mode" which needs to be covered so it is very hard to tell what is the realistic date, sorry.

Did the colleagues from PD configures the filters to be the same for both search and navigation?

**Comment by sja-dS** [comment]
Hey @a-laurowski 
Yes, meanwhile they enabled temporary the Filters for Search.
But for our Customer it isn't the best Solution to have all Filters also on Search, because it can happen that for general Searches to many Filters are shown and that it's could be a bit overwhelming for the customer

**Comment by a-laurowski** [comment]
Hi @sja-dS 
I'm writing because i have some contradiction information about this problem is solved or not. In our internal ticket system it is closed and i've been told that you solved the problem the other way. It's from October last year. 

Today, i've been told that you were asking about that. So i'm here to explain the situation.

Starting from version 2.3.3, an `ff-communication` attribute `category-page` introduced in Web Components [4.0.3](https://github.com/FACT-Finder-Web-Components/ff-web-components/releases/tag/4.0.4) is being supported.
How the `category-page` is working you can read https://web-components.fact-finder.de/documentation/4.x/category-pages

After specifying the  `category-page` attribute with a category filter, the Web Components starts working in category page mode, which means any request will contain the predefined category filter.
Also the `navigation` endpoint will be used instead of `search` which was the origin of that issue.

Please let me know if implementing `category-page` fixed the problem

**Comment by sja-dS** [comment]
Hey @a-laurowski 
Thank you for pointing that out. I passed this reply to my Project Manager as I'm no longer part of this Project.
He will get in touch with you
