### ISSUE TITLE
FFWEB-998 : cleanValue removes Umlauts (etc.) from description

### ISSUE THREAD

**Issue by fritzmg** [FACT-Finder-Web-Components/magento2-module#54]
The current implementation of `Omikron\Factfinder\Helper\Product::cleanValue` removes a lot of characters from the description and short description:
```php
// do not allow special chars in values
$value = preg_replace('/([^A-Za-z0-9 -])+/', '', $value);
```
However, obviously this is not acceptable for any non-English store, since it also removes Umlauts or other language specific characters.

**Comment by a-laurowski** [comment]
@fritzmg 
I think the best solution of solving this is to make this regular expression  configurable (from admin panel). and if it will be null, the script just doesn't  execute mentioned preg_replace function., otherwise it execute preg_replace with customized regular expression pattern saved in store config

**Comment by fritzmg** [comment]
Hm, I don't know, but shouldn't the default regular expression be changed regardless? I mean it's pretty unusable if a text like
```
Auch für die pikante Küche wie z.B. zur Abrundung von Suppen und Saucen ist es geeignet.
```
gets exported to FACT Finder as
```
Auch fr die pikante Kche wie z.B. zur Abrundung von Suppen und Saucen ist es geeignet.
```
May the export should be changed to another format anyway. CSV exports/imports are pretty out of date, I think it would be better to use JSON as the import/export format, which has a well defined definition and handling for 'special characters'.

**Comment by a-laurowski** [comment]
@fritzmg 
I meant this preg_replace should not be executed unless customer defines some regular expression in admin panel.
Something like this:
```
if ($regularExpression = $this->helper->getRegularExpressionForCleanValue()) {
    $value = preg_replace(regularExpression, '', $value);
}

```

Feel free to create new issue for supporting JSON format export. Hovewer, the CSV export should remain because it described in documentation as primary format. 
https://doku.fact-finder.de/endoc/latest/fact-finder-integration/export-guide/data-export-fundamentals

**Comment by fritzmg** [comment]
> I meant this preg_replace should not be executed unless customer defines some regular expression in admin panel.

Ah yes, but you need at least _some_ regular expression, otherwise illegal characters like `"`, `;`, `\n` might be exported to the CSV, which would break the export file.

**Comment by fritzmg** [comment]
This is also a problem for singular fields that contain Umlauts. For instance we have a field that contains the name of the Austrian federal state, which will be used as a filter. However, the available filter options will then only show

* Niedersterreich
* Obersterreich
* Krnten

instead of

* Niederösterreich
* Oberösterreich
* Kärnten

**Comment by fritzmg** [comment]
I'll close this for now since #84 also contained a change regarding the `cleanValue` function, allowing also at least Umlauts.
